//! The model's TypeScript and JSON Schema, generated from the same serde
//! attributes as the wire format.
//!
//! Both are committed and checked for drift by this crate's tests:
//!
//! - [`TYPESCRIPT_PATH`], for the viewer's frontend;
//! - [`JSON_SCHEMA_PATH`], for Python and ML consumers of the native format.
//!
//! `cargo run -p dcmview-annotation --example generate_annotation_model`
//! rewrites them; with `--check` it fails when either is stale.

/// Where the generated TypeScript is committed, relative to the repository
/// root.
pub const TYPESCRIPT_PATH: &str = "frontend/src/generated/annotation-types.ts";

/// Where the generated JSON Schema is committed, relative to the repository
/// root.
pub const JSON_SCHEMA_PATH: &str =
    "crates/dcmview-annotation/schema/dcmview.annotations.schema.json";

/// The TypeScript declarations of every wire type of the model.
///
/// The roots are [`crate::Document`], [`crate::OpEnvelope`],
/// [`crate::ApplyResult`] and [`crate::FrameSet`]; every derived type they
/// reach is declared once. `FrameSet` is a root of its own because
/// [`crate::FrameScope`] states its TypeScript by hand
/// (`"all" | FrameSet`), which hides the dependency from ts-rs.
///
/// The layout is the one `examples/generate_api_types.rs` of the root
/// package uses: a two-line `//` header saying the file is generated, by
/// which command, and must not be edited; then one `export type` per Rust
/// type, each preceded by its documentation, sorted by TypeScript name and
/// separated by one blank line. Integers are `number` (every integer on the
/// wire is below 2^53). The text ends with one newline and is the same on
/// every platform and every run. It must type check on its own under the
/// frontend's `tsc --noEmit`.
pub fn typescript() -> String {
    let config = ts_rs::Config::new().with_large_int("number");
    let mut declarations = Declarations {
        config: &config,
        seen: std::collections::HashSet::new(),
        by_name: std::collections::BTreeMap::new(),
    };
    use ts_rs::TypeVisitor;
    declarations.visit::<crate::Document>();
    declarations.visit::<crate::OpEnvelope>();
    declarations.visit::<crate::ApplyResult>();
    declarations.visit::<crate::FrameSet>();
    let mut text = String::from("// Generated by `cargo run -p dcmview-annotation --example generate_annotation_model`.\n// Do not edit this file directly.\n\n");
    text.push_str(
        &declarations
            .by_name
            .into_values()
            .collect::<Vec<_>>()
            .join("\n\n"),
    );
    text.push('\n');
    text
}

/// The JSON Schema (draft 2020-12) of [`crate::Document`], as schemars
/// derives it, pretty printed with serde_json and ending with one newline.
/// The same on every platform and every run.
pub fn json_schema() -> String {
    let schema = schemars::schema_for!(crate::Document);
    // Schema serializes only JSON values, with string object keys, so the
    // serializer has no fallible model numbers or custom values to visit.
    let mut text = serde_json::to_string_pretty(&schema).unwrap_or_default();
    text.push('\n');
    text
}

struct Declarations<'a> {
    config: &'a ts_rs::Config,
    seen: std::collections::HashSet<std::any::TypeId>,
    by_name: std::collections::BTreeMap<String, String>,
}

impl ts_rs::TypeVisitor for Declarations<'_> {
    fn visit<T: ts_rs::TS + 'static + ?Sized>(&mut self) {
        if !self.seen.insert(std::any::TypeId::of::<T>()) {
            return;
        }
        if T::output_path().is_some() {
            let docs = T::docs().unwrap_or_default();
            let declaration = format!("{docs}export {}", T::decl(self.config));
            self.by_name.insert(T::ident(self.config), declaration);
        }
        T::visit_dependencies(self);
    }
}
