//! Writes `frontend/src/generated/api-types.ts` from `src/api/contracts.rs`.
//!
//! `cargo run --example generate_api_types` rewrites the file; with `--check`
//! it exits non-zero when the committed file differs from the Rust contract.

use dcmview::api::contracts::{
    endpoints, DoseOverlayQuery, EmbedRoiAnnotations, ErrorResponse, FilesResponse, FrameInfo,
    FrameQuery, FrameValueMapping, FrameWindowApplied, GraphicAnnotationsQuery,
    GraphicAnnotationsResponse, HealthResponse, ParametricMapOverlayQuery, PixelQuery,
    RawFrameMetadata, ReferenceCatalogResponse, SemanticContextResponse, SeriesCatalogResponse,
    TagNode, TagQuery, WsiFrameContextResponse, API_PREFIX, API_RESPONSE_HEADERS,
    DISPLAY_FRAME_HEADERS, RAW_FRAME_HEADERS,
};
use std::any::TypeId;
use std::collections::{BTreeMap, HashSet};
use std::fmt::Write as _;
use std::path::Path;
use std::process::ExitCode;
use ts_rs::{Config, TypeVisitor, TS};

const OUTPUT: &str = "frontend/src/generated/api-types.ts";

/// Collects the declaration of every derived type reachable from the roots,
/// so nested wire types need no separate listing. Declarations are keyed by
/// TypeScript name because ts-rs does not visit dependencies in a stable order.
struct Declarations<'a> {
    config: &'a Config,
    seen: HashSet<TypeId>,
    by_name: BTreeMap<String, String>,
}

impl TypeVisitor for Declarations<'_> {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        if !self.seen.insert(TypeId::of::<T>()) {
            return;
        }
        // Only derived types have an output path; primitives and containers
        // such as `Vec<T>` or `Option<T>` are inlined but still visited for
        // the types they contain.
        if T::output_path().is_some() {
            let docs = T::docs().unwrap_or_default();
            let declaration = format!("{docs}export {}", T::decl(self.config));
            self.by_name.insert(T::ident(self.config), declaration);
        }
        T::visit_dependencies(self);
    }
}

fn render() -> String {
    // Every integer on the wire is a JSON number well below 2^53.
    let config = Config::new().with_large_int("number");
    let mut declarations = Declarations {
        config: &config,
        seen: HashSet::new(),
        by_name: BTreeMap::new(),
    };
    declarations.visit::<HealthResponse>();
    declarations.visit::<FilesResponse>();
    declarations.visit::<SeriesCatalogResponse>();
    declarations.visit::<FrameInfo>();
    declarations.visit::<ReferenceCatalogResponse>();
    declarations.visit::<SemanticContextResponse>();
    declarations.visit::<FrameValueMapping>();
    declarations.visit::<WsiFrameContextResponse>();
    declarations.visit::<FrameQuery>();
    declarations.visit::<FrameWindowApplied>();
    declarations.visit::<DoseOverlayQuery>();
    declarations.visit::<ParametricMapOverlayQuery>();
    declarations.visit::<GraphicAnnotationsQuery>();
    declarations.visit::<GraphicAnnotationsResponse>();
    declarations.visit::<RawFrameMetadata>();
    declarations.visit::<TagNode>();
    declarations.visit::<TagQuery>();
    declarations.visit::<PixelQuery>();
    declarations.visit::<EmbedRoiAnnotations>();
    declarations.visit::<ErrorResponse>();

    let mut out = String::from(
        "// Generated by `cargo run --example generate_api_types` from src/api/contracts.rs.\n\
         // Do not edit this file directly.\n\n",
    );

    out.push_str("export const API_ENDPOINTS = {\n");
    for endpoint in endpoints::ALL {
        writeln!(
            out,
            "\t{}: {{ method: \"{}\", path: \"{API_PREFIX}{}\" }},",
            endpoint.id,
            endpoint.method.as_str(),
            endpoint.path
        )
        .expect("write to string");
    }
    out.push_str("} as const;\n\n");

    out.push_str("export const API_RESPONSE_HEADERS = {\n");
    for (field, name) in API_RESPONSE_HEADERS {
        writeln!(out, "\t{field}: \"{name}\",").expect("write to string");
    }
    out.push_str("} as const;\n\n");

    out.push_str("export const DISPLAY_FRAME_HEADERS = {\n");
    for (field, name) in DISPLAY_FRAME_HEADERS {
        writeln!(out, "\t{field}: \"{name}\",").expect("write to string");
    }
    out.push_str("} as const;\n\n");

    out.push_str("export const RAW_FRAME_HEADERS = {\n");
    for (field, name) in RAW_FRAME_HEADERS {
        writeln!(out, "\t{field}: \"{name}\",").expect("write to string");
    }
    out.push_str("} as const satisfies Record<keyof RawFrameMetadata, string>;\n\n");

    let declarations = declarations.by_name.into_values().collect::<Vec<_>>();
    out.push_str(&declarations.join("\n\n"));
    out.push('\n');
    out
}

fn main() -> ExitCode {
    let check = std::env::args()
        .skip(1)
        .any(|argument| argument == "--check");
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(OUTPUT);
    let rendered = render();

    if check {
        let current = std::fs::read_to_string(&path).unwrap_or_default();
        if current.replace("\r\n", "\n") != rendered {
            eprintln!(
                "{OUTPUT} is stale; regenerate it with `cargo run --example generate_api_types`"
            );
            return ExitCode::FAILURE;
        }
        return ExitCode::SUCCESS;
    }

    std::fs::write(&path, rendered).expect("write generated API types");
    ExitCode::SUCCESS
}
